actual: Bacteria	58	77	Lactobacillus casei
expect: Bacteria	58	92	Lactobacillus casei strain Shirota
actual: Habitat	149	171	intestinal environment
expect: Habitat	149	211	intestinal environment of healthy individuals with soft stools
actual: Habitat	175	194	healthy individuals
expect: Habitat	175	211	healthy individuals with soft stools
actual: Habitat	205	211	stools
expect: Habitat	200	211	soft stools
actual: Habitat	239	253	fermented milk
expect: Habitat	239	262	fermented milk beverage
actual: Bacteria	277	296	Lactobacillus casei
expect: Bacteria	277	311	Lactobacillus casei strain Shirota
actual: Habitat	449	471	intestinal environment
expect: Habitat	449	511	intestinal environment of healthy individuals with soft stools
actual: Habitat	475	494	healthy individuals
expect: Habitat	475	511	healthy individuals with soft stools
actual: Habitat	505	511	stools
expect: Habitat	500	511	soft stools
actual: Habitat	568	574	stools
expect: Habitat	563	574	soft stools
actual: Habitat	1778	1797	healthy individuals
expect: Habitat	1778	1813	healthy individuals with soft stool
actual: Habitat	1808	1813	stool
expect: Habitat	1803	1813	soft stool
